# Generated by Django 3.0.4 on 2020-03-29 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_auto_20200329_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marcas',
            new_name='Marca',
        ),
    ]
