# Generated by Django 3.0.4 on 2020-03-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20200329_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marcas',
        ),
    ]
