# Generated by Django 3.0.4 on 2020-04-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_facturadetalle_facturaencabezado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadetalle',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de Supervisor de Caja Detalle')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
        migrations.AlterModelOptions(
            name='facturaencabezado',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Encabezado')], 'verbose_name': 'Encabezado Factura', 'verbose_name_plural': 'Encabezado Facturas'},
        ),
    ]
